//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskFlow.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewModelsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModelsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskFlow.Resources.Resources.ViewModelsResource", typeof(ViewModelsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title_Display {
            get {
                return ResourceManager.GetString("Title_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Title.
        /// </summary>
        public static string Title_Required {
            get {
                return ResourceManager.GetString("Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot exceed 200 characters.
        /// </summary>
        public static string Title_MaxLength {
            get {
                return ResourceManager.GetString("Title_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_Display {
            get {
                return ResourceManager.GetString("Description_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Description.
        /// </summary>
        public static string Description_Required {
            get {
                return ResourceManager.GetString("Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed 2000 characters.
        /// </summary>
        public static string Description_MaxLength {
            get {
                return ResourceManager.GetString("Description_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate_Display {
            get {
                return ResourceManager.GetString("DueDate_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority_Display {
            get {
                return ResourceManager.GetString("Priority_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Priority.
        /// </summary>
        public static string Priority_Required {
            get {
                return ResourceManager.GetString("Priority_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority must be between 1 and 5.
        /// </summary>
        public static string Priority_Range {
            get {
                return ResourceManager.GetString("Priority_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string IsCompleted_Display {
            get {
                return ResourceManager.GetString("IsCompleted_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project_Display {
            get {
                return ResourceManager.GetString("Project_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category_Display {
            get {
                return ResourceManager.GetString("Category_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status_Display {
            get {
                return ResourceManager.GetString("Status_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Status.
        /// </summary>
        public static string Status_Required {
            get {
                return ResourceManager.GetString("Status_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email_Display {
            get {
                return ResourceManager.GetString("Email_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Email.
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password_Display {
            get {
                return ResourceManager.GetString("Password_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Password.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum is 8 characters.
        /// </summary>
        public static string Password_MinLength {
            get {
                return ResourceManager.GetString("Password_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_Display {
            get {
                return ResourceManager.GetString("Name_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Name.
        /// </summary>
        public static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed 100 characters.
        /// </summary>
        public static string Name_MaxLength {
            get {
                return ResourceManager.GetString("Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic).
        /// </summary>
        public static string NameAr_Display {
            get {
                return ResourceManager.GetString("NameAr_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Name (Arabic).
        /// </summary>
        public static string NameAr_Required {
            get {
                return ResourceManager.GetString("NameAr_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic) cannot exceed 100 characters.
        /// </summary>
        public static string NameAr_MaxLength {
            get {
                return ResourceManager.GetString("NameAr_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName_Display {
            get {
                return ResourceManager.GetString("ProjectName_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Project Name.
        /// </summary>
        public static string ProjectName_Required {
            get {
                return ResourceManager.GetString("ProjectName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name cannot exceed 100 characters.
        /// </summary>
        public static string ProjectName_MaxLength {
            get {
                return ResourceManager.GetString("ProjectName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName_Display {
            get {
                return ResourceManager.GetString("CategoryName_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Category Name.
        /// </summary>
        public static string CategoryName_Required {
            get {
                return ResourceManager.GetString("CategoryName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name cannot exceed 100 characters.
        /// </summary>
        public static string CategoryName_MaxLength {
            get {
                return ResourceManager.GetString("CategoryName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color_Display {
            get {
                return ResourceManager.GetString("Color_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Approved_Display {
            get {
                return ResourceManager.GetString("Approved_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive_Display {
            get {
                return ResourceManager.GetString("IsActive_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate_Display {
            get {
                return ResourceManager.GetString("CreationDate_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Field.
        /// </summary>
        public static string Required_Field {
            get {
                return ResourceManager.GetString("Required_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Name (English).
        /// </summary>
        public static string StatusNameEn_Display {
            get {
                return ResourceManager.GetString("StatusNameEn_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Status name in English.
        /// </summary>
        public static string StatusNameEn_Required {
            get {
                return ResourceManager.GetString("StatusNameEn_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status name in English cannot exceed 20 characters.
        /// </summary>
        public static string StatusNameEn_MaxLength {
            get {
                return ResourceManager.GetString("StatusNameEn_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Name (Arabic).
        /// </summary>
        public static string StatusNameAr_Display {
            get {
                return ResourceManager.GetString("StatusNameAr_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Status name in Arabic.
        /// </summary>
        public static string StatusNameAr_Required {
            get {
                return ResourceManager.GetString("StatusNameAr_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status name in Arabic cannot exceed 20 characters.
        /// </summary>
        public static string StatusNameAr_MaxLength {
            get {
                return ResourceManager.GetString("StatusNameAr_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name (English).
        /// </summary>
        public static string RoleNameEn_Display {
            get {
                return ResourceManager.GetString("RoleNameEn_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Role name in English.
        /// </summary>
        public static string RoleNameEn_Required {
            get {
                return ResourceManager.GetString("RoleNameEn_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name in English cannot exceed 25 characters.
        /// </summary>
        public static string RoleNameEn_MaxLength {
            get {
                return ResourceManager.GetString("RoleNameEn_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name (Arabic).
        /// </summary>
        public static string RoleNameAr_Display {
            get {
                return ResourceManager.GetString("RoleNameAr_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Role name in Arabic.
        /// </summary>
        public static string RoleNameAr_Required {
            get {
                return ResourceManager.GetString("RoleNameAr_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name in Arabic cannot exceed 25 characters.
        /// </summary>
        public static string RoleNameAr_MaxLength {
            get {
                return ResourceManager.GetString("RoleNameAr_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the RoleName.
        /// </summary>
        public static string User_Role_NameRequired {
            get {
                return ResourceManager.GetString("User_Role_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the RoleName In Arabic.
        /// </summary>
        public static string User_Role_NameRequiredAr {
            get {
                return ResourceManager.GetString("User_Role_NameRequiredAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter English letters only.
        /// </summary>
        public static string CompanyNameEn_EnglishOnly {
            get {
                return ResourceManager.GetString("CompanyNameEn_EnglishOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter arabic letters only.
        /// </summary>
        public static string CompanyNameAr_ArabicOnly {
            get {
                return ResourceManager.GetString("CompanyNameAr_ArabicOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TaskCount_Display {
            get {
                return ResourceManager.GetString("TaskCount_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword_Display {
            get {
                return ResourceManager.GetString("ConfirmPassword_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string ConfirmPassword_NotMatch {
            get {
                return ResourceManager.GetString("ConfirmPassword_NotMatch", resourceCulture);
            }
        }
    }
}
