//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskFlow.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthResource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthResource() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskFlow.Resources.AuthResource", typeof(AuthResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        public static string Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Login_InvalidCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string Login_UnexpectedError {
            get {
                return ResourceManager.GetString("Login_UnexpectedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have been logged out.
        /// </summary>
        public static string Logout_Success {
            get {
                return ResourceManager.GetString("Logout_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string SignUp_Title {
            get {
                return ResourceManager.GetString("SignUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SignUp_Name {
            get {
                return ResourceManager.GetString("SignUp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic).
        /// </summary>
        public static string SignUp_NameAr {
            get {
                return ResourceManager.GetString("SignUp_NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string SignUp_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUp_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string SignUp_Button {
            get {
                return ResourceManager.GetString("SignUp_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created successfully!.
        /// </summary>
        public static string SignUp_Success {
            get {
                return ResourceManager.GetString("SignUp_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already registered.
        /// </summary>
        public static string SignUp_EmailExists {
            get {
                return ResourceManager.GetString("SignUp_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string SignUp_HaveAccount {
            get {
                return ResourceManager.GetString("SignUp_HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignUp_LoginLink {
            get {
                return ResourceManager.GetString("SignUp_LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create account. Please try again..
        /// </summary>
        public static string SignUp_Failed {
            get {
                return ResourceManager.GetString("SignUp_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user role configured. Please contact the administrator..
        /// </summary>
        public static string SignUp_NoRole {
            get {
                return ResourceManager.GetString("SignUp_NoRole", resourceCulture);
            }
        }
    }
}
