//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskFlow.Resources {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResource() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskFlow.Resources.DashboardResource", typeof(DashboardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string DashboardTitle { get { return ResourceManager.GetString("DashboardTitle", resourceCulture); } }
        public static string ManageTodos { get { return ResourceManager.GetString("ManageTodos", resourceCulture); } }
        public static string AddTodo { get { return ResourceManager.GetString("AddTodo", resourceCulture); } }
        public static string EditTodo { get { return ResourceManager.GetString("EditTodo", resourceCulture); } }
        public static string DeleteTodo { get { return ResourceManager.GetString("DeleteTodo", resourceCulture); } }
        public static string TodoList { get { return ResourceManager.GetString("TodoList", resourceCulture); } }
        public static string ViewDetails { get { return ResourceManager.GetString("ViewDetails", resourceCulture); } }
        public static string QuickSearch { get { return ResourceManager.GetString("QuickSearch", resourceCulture); } }
        public static string Actions { get { return ResourceManager.GetString("Actions", resourceCulture); } }
        public static string Save { get { return ResourceManager.GetString("Save", resourceCulture); } }
        public static string Cancel { get { return ResourceManager.GetString("Cancel", resourceCulture); } }
        public static string Edit { get { return ResourceManager.GetString("Edit", resourceCulture); } }
        public static string Delete { get { return ResourceManager.GetString("Delete", resourceCulture); } }
        public static string Details { get { return ResourceManager.GetString("Details", resourceCulture); } }
        public static string Active { get { return ResourceManager.GetString("Active", resourceCulture); } }
        public static string Inactive { get { return ResourceManager.GetString("Inactive", resourceCulture); } }
        public static string NoData { get { return ResourceManager.GetString("NoData", resourceCulture); } }
        public static string AreYouSure { get { return ResourceManager.GetString("AreYouSure", resourceCulture); } }
        public static string YesDelete { get { return ResourceManager.GetString("YesDelete", resourceCulture); } }
        public static string TodoInsertSuccess { get { return ResourceManager.GetString("TodoInsertSuccess", resourceCulture); } }
        public static string TodoInsertFailed { get { return ResourceManager.GetString("TodoInsertFailed", resourceCulture); } }
        public static string TodoUpdateSuccess { get { return ResourceManager.GetString("TodoUpdateSuccess", resourceCulture); } }
        public static string TodoUpdateFailed { get { return ResourceManager.GetString("TodoUpdateFailed", resourceCulture); } }
        public static string TodoDeleteSuccess { get { return ResourceManager.GetString("TodoDeleteSuccess", resourceCulture); } }
        public static string TodoDeleteFailed { get { return ResourceManager.GetString("TodoDeleteFailed", resourceCulture); } }
        public static string ManageProjects { get { return ResourceManager.GetString("ManageProjects", resourceCulture); } }
        public static string AddProject { get { return ResourceManager.GetString("AddProject", resourceCulture); } }
        public static string EditProject { get { return ResourceManager.GetString("EditProject", resourceCulture); } }
        public static string DeleteProject { get { return ResourceManager.GetString("DeleteProject", resourceCulture); } }
        public static string ProjectInsertSuccess { get { return ResourceManager.GetString("ProjectInsertSuccess", resourceCulture); } }
        public static string ProjectInsertFailed { get { return ResourceManager.GetString("ProjectInsertFailed", resourceCulture); } }
        public static string ProjectUpdateSuccess { get { return ResourceManager.GetString("ProjectUpdateSuccess", resourceCulture); } }
        public static string ProjectUpdateFailed { get { return ResourceManager.GetString("ProjectUpdateFailed", resourceCulture); } }
        public static string ProjectDeleteSuccess { get { return ResourceManager.GetString("ProjectDeleteSuccess", resourceCulture); } }
        public static string ProjectDeleteFailed { get { return ResourceManager.GetString("ProjectDeleteFailed", resourceCulture); } }
        public static string ManageCategories { get { return ResourceManager.GetString("ManageCategories", resourceCulture); } }
        public static string AddCategory { get { return ResourceManager.GetString("AddCategory", resourceCulture); } }
        public static string EditCategory { get { return ResourceManager.GetString("EditCategory", resourceCulture); } }
        public static string DeleteCategory { get { return ResourceManager.GetString("DeleteCategory", resourceCulture); } }
        public static string CategoryInsertSuccess { get { return ResourceManager.GetString("CategoryInsertSuccess", resourceCulture); } }
        public static string CategoryInsertFailed { get { return ResourceManager.GetString("CategoryInsertFailed", resourceCulture); } }
        public static string CategoryUpdateSuccess { get { return ResourceManager.GetString("CategoryUpdateSuccess", resourceCulture); } }
        public static string CategoryUpdateFailed { get { return ResourceManager.GetString("CategoryUpdateFailed", resourceCulture); } }
        public static string CategoryDeleteSuccess { get { return ResourceManager.GetString("CategoryDeleteSuccess", resourceCulture); } }
        public static string CategoryDeleteFailed { get { return ResourceManager.GetString("CategoryDeleteFailed", resourceCulture); } }
        public static string ManageStatuses { get { return ResourceManager.GetString("ManageStatuses", resourceCulture); } }
        public static string AddStatus { get { return ResourceManager.GetString("AddStatus", resourceCulture); } }
        public static string EditStatus { get { return ResourceManager.GetString("EditStatus", resourceCulture); } }
        public static string DeleteStatus { get { return ResourceManager.GetString("DeleteStatus", resourceCulture); } }
        public static string StatusInsertSuccess { get { return ResourceManager.GetString("StatusInsertSuccess", resourceCulture); } }
        public static string StatusInsertFailed { get { return ResourceManager.GetString("StatusInsertFailed", resourceCulture); } }
        public static string StatusUpdateSuccess { get { return ResourceManager.GetString("StatusUpdateSuccess", resourceCulture); } }
        public static string StatusUpdateFailed { get { return ResourceManager.GetString("StatusUpdateFailed", resourceCulture); } }
        public static string StatusDeleteSuccess { get { return ResourceManager.GetString("StatusDeleteSuccess", resourceCulture); } }
        public static string StatusDeleteFailed { get { return ResourceManager.GetString("StatusDeleteFailed", resourceCulture); } }
        public static string StatusAlreadyExists { get { return ResourceManager.GetString("StatusAlreadyExists", resourceCulture); } }
        public static string StatusInUseCannotDelete { get { return ResourceManager.GetString("StatusInUseCannotDelete", resourceCulture); } }
        public static string TotalTasks { get { return ResourceManager.GetString("TotalTasks", resourceCulture); } }
        public static string CompletedTasks { get { return ResourceManager.GetString("CompletedTasks", resourceCulture); } }
        public static string PendingTasks { get { return ResourceManager.GetString("PendingTasks", resourceCulture); } }
        public static string OverdueTasks { get { return ResourceManager.GetString("OverdueTasks", resourceCulture); } }
        public static string WelcomeMessage { get { return ResourceManager.GetString("WelcomeMessage", resourceCulture); } }
        public static string Logout { get { return ResourceManager.GetString("Logout", resourceCulture); } }
        public static string ManageUserRoles { get { return ResourceManager.GetString("ManageUserRoles", resourceCulture); } }
        public static string AddRole { get { return ResourceManager.GetString("AddRole", resourceCulture); } }
        public static string EditRole { get { return ResourceManager.GetString("EditRole", resourceCulture); } }
        public static string DeleteRole { get { return ResourceManager.GetString("DeleteRole", resourceCulture); } }
        public static string RoleInsertSuccess { get { return ResourceManager.GetString("RoleInsertSuccess", resourceCulture); } }
        public static string RoleInsertFailed { get { return ResourceManager.GetString("RoleInsertFailed", resourceCulture); } }
        public static string RoleUpdateSuccess { get { return ResourceManager.GetString("RoleUpdateSuccess", resourceCulture); } }
        public static string RoleUpdateFailed { get { return ResourceManager.GetString("RoleUpdateFailed", resourceCulture); } }
        public static string RoleDeleteSuccess { get { return ResourceManager.GetString("RoleDeleteSuccess", resourceCulture); } }
        public static string RoleDeleteFailed { get { return ResourceManager.GetString("RoleDeleteFailed", resourceCulture); } }
        public static string RoleNameExists { get { return ResourceManager.GetString("RoleNameExists", resourceCulture); } }
        public static string InUse { get { return ResourceManager.GetString("InUse", resourceCulture); } }
        public static string Users { get { return ResourceManager.GetString("Users", resourceCulture); } }
        public static string ManageUsers { get { return ResourceManager.GetString("ManageUsers", resourceCulture); } }
        public static string AddUser { get { return ResourceManager.GetString("AddUser", resourceCulture); } }
        public static string EditUser { get { return ResourceManager.GetString("EditUser", resourceCulture); } }
        public static string DeleteUser { get { return ResourceManager.GetString("DeleteUser", resourceCulture); } }
        public static string UserInsertSuccess { get { return ResourceManager.GetString("UserInsertSuccess", resourceCulture); } }
        public static string UserInsertFailed { get { return ResourceManager.GetString("UserInsertFailed", resourceCulture); } }
        public static string UserUpdateSuccess { get { return ResourceManager.GetString("UserUpdateSuccess", resourceCulture); } }
        public static string UserUpdateFailed { get { return ResourceManager.GetString("UserUpdateFailed", resourceCulture); } }
        public static string UserDeleteSuccess { get { return ResourceManager.GetString("UserDeleteSuccess", resourceCulture); } }
        public static string UserDeleteFailed { get { return ResourceManager.GetString("UserDeleteFailed", resourceCulture); } }
        public static string UserNotFound { get { return ResourceManager.GetString("UserNotFound", resourceCulture); } }
        public static string Confirminsert { get { return ResourceManager.GetString("Confirminsert", resourceCulture); } }
        public static string insertItem { get { return ResourceManager.GetString("insertItem", resourceCulture); } }
        public static string Yes { get { return ResourceManager.GetString("Yes", resourceCulture); } }
        public static string Confirmed { get { return ResourceManager.GetString("Confirmed", resourceCulture); } }
        public static string ConfirmUpdateStatus { get { return ResourceManager.GetString("ConfirmUpdateStatus", resourceCulture); } }
        public static string YesUpdateStatus { get { return ResourceManager.GetString("YesUpdateStatus", resourceCulture); } }
        public static string StatusName { get { return ResourceManager.GetString("StatusName", resourceCulture); } }
        public static string StatusNameAr { get { return ResourceManager.GetString("StatusNameAr", resourceCulture); } }
        public static string Status { get { return ResourceManager.GetString("Status", resourceCulture); } }
        public static string ActiveStatus { get { return ResourceManager.GetString("ActiveStatus", resourceCulture); } }
        public static string InactiveStatus { get { return ResourceManager.GetString("InactiveStatus", resourceCulture); } }
        public static string NoStatusesAvailable { get { return ResourceManager.GetString("NoStatusesAvailable", resourceCulture); } }
        public static string WelcomeToTaskFlow { get { return ResourceManager.GetString("WelcomeToTaskFlow", resourceCulture); } }
        public static string TaskFlowDescription { get { return ResourceManager.GetString("TaskFlowDescription", resourceCulture); } }
        public static string GetStarted { get { return ResourceManager.GetString("GetStarted", resourceCulture); } }
    }
}
